### ISSUE TITLE
Build fails with setuptools 65.5.0

### ISSUE THREAD

**Issue by EdwardBetts** [ua-parser/uap-python#144]
```
$ python3 ./setup.py build
/home/edward/src/2022/vendor/uap-python/./setup.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils import log
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/edward/src/2022/vendor/uap-python/./setup.py", line 201, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 474, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1107, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 540, in _parse_command_opts
    raise DistutilsClassError(
distutils.errors.DistutilsClassError: command class <class '__main__.build'> must subclass Command
$

```

Here is the bug in the Debian bug tracking system: https://bugs.debian.org/1022474

**Comment by masklinn** [comment]
@EdwardBetts heya, sorry for the delay replying.

I can not reproduce the issue, even after updating setuptools to 65.5.0:
```
> pip list  | grep setuptools
setuptools   65.5.0
> python setup.py build
running build
running build_regexes
~.pyenv/versions/uap-310/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
initializing git submodules
compiling regexes.yaml -> _regexes.py
running build_py
running egg_info
writing ua_parser.egg-info/PKG-INFO
writing dependency_links to ua_parser.egg-info/dependency_links.txt
writing top-level names to ua_parser.egg-info/top_level.txt
reading manifest file 'ua_parser.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
writing manifest file 'ua_parser.egg-info/SOURCES.txt'
warning: build_py: byte-compiling is disabled, skipping.
```
Furthermore the bespoke command class (`build_regexes`) extends `distutils.core.Command` while the rest extend the corresponding setuptools commands (in order to run the regex build), unless setuptools has broken their own command classes that seems unlikely. Which version of Python are you building with?

**Comment by EdwardBetts** [comment]
Python 3.10.8

I'll keep looking and try and work out why it isn't working on my machine.

**Comment by masklinn** [comment]
> I'll keep looking and try and work out why it isn't working on my machine.

The warning seems to be emitted by https://github.com/python/cpython/blob/3.10/Lib/distutils/dist.py#L543-L547 so the superclass it expects is [`distutils.cmd.Command`](https://github.com/python/cpython/blob/3.10/Lib/distutils/dist.py#L526-L527), might be useful to run under pdb (or some other debugger) and try to set a breakpoint, in order to see what `cmd_class` it's receiving.
