### ISSUE TITLE
Fails to build in virtualenv

### ISSUE THREAD

**Issue by ColtonProvias** [ua-parser/uap-python#31]
Attempting to install ua-parser-0.5 on Python 3.5.0 on Mac OS X 10.11.1 and getting the following error:

```
(MyNewLeaf)MyNewLeaf|store-admin⚡ ⇒ pip install --upgrade ua-parser
Collecting ua-parser
  Using cached ua-parser-0.5.0.tar.gz
Requirement already up-to-date: pyyaml in ./lib/python3.5/site-packages (from ua-parser)
Building wheels for collected packages: ua-parser
  Running setup.py bdist_wheel for ua-parser
  Complete output from command /Users/coltonprovias/Development/MyNewLeaf/bin/python3.5 -c "import setuptools;__file__='/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/tmpe4yexrdlpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/ua_parser
  copying ./ua_parser/__init__.py -> build/lib/ua_parser
  copying ./ua_parser/user_agent_parser.py -> build/lib/ua_parser
  copying ./ua_parser/user_agent_parser_test.py -> build/lib/ua_parser
  running egg_info
  writing dependency_links to ua_parser.egg-info/dependency_links.txt
  writing top-level names to ua_parser.egg-info/top_level.txt
  writing requirements to ua_parser.egg-info/requires.txt
  writing ua_parser.egg-info/PKG-INFO
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'ua_parser.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ua_parser.egg-info/SOURCES.txt'
  copying ./ua_parser/regexes.yaml -> build/lib/ua_parser
  copying ./ua_parser/regexes.json -> build/lib/ua_parser
  installing to build/bdist.macosx-10.11-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py", line 83, in <module>
      'Programming Language :: Python :: Implementation :: PyPy',
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/coltonprovias/Development/MyNewLeaf/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 211, in run
      self.run_command('install')
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py", line 43, in run
      install_regexes()
    File "/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py", line 16, in install_regexes
      'Unable to find regexes.yaml, should be at %r' % yaml_src)
  RuntimeError: Unable to find regexes.yaml, should be at '/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/uap-core/regexes.yaml'
  Copying regexes.yaml to package directory...
  
  ----------------------------------------
  Failed building wheel for ua-parser
Failed to build ua-parser
Installing collected packages: ua-parser
  Found existing installation: ua-parser 0.4.1
    Uninstalling ua-parser-0.4.1:
      Successfully uninstalled ua-parser-0.4.1
  Running setup.py install for ua-parser
    Complete output from command /Users/coltonprovias/Development/MyNewLeaf/bin/python3.5 -c "import setuptools, tokenize;__file__='/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-m56ggvi8-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/coltonprovias/Development/MyNewLeaf/bin/../include/site/python3.5/ua-parser:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py", line 83, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py", line 43, in run
        install_regexes()
      File "/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py", line 16, in install_regexes
        'Unable to find regexes.yaml, should be at %r' % yaml_src)
    RuntimeError: Unable to find regexes.yaml, should be at '/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/uap-core/regexes.yaml'
    Copying regexes.yaml to package directory...
    
    ----------------------------------------
  Rolling back uninstall of ua-parser
Command "/Users/coltonprovias/Development/MyNewLeaf/bin/python3.5 -c "import setuptools, tokenize;__file__='/private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-m56ggvi8-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/coltonprovias/Development/MyNewLeaf/bin/../include/site/python3.5/ua-parser" failed with error code 1 in /private/var/folders/zl/0vgdj8l96ss0_w20j9k0t7bm0000gn/T/pip-build-x3p3uu52/ua-parser
```

**Comment by beruic** [comment]
I get the same error on Windows: `Unable to find regexes.yaml`

**Comment by jmagnusson** [comment]
Same problem here.

**Comment by kr41** [comment]
This https://github.com/ua-parser/uap-python/commit/7f2e72f19a3f3bcb100ac29181b6f24844025e83 fixes the issue, but why it has not been released on PyPI yet?

**Comment by dsimandl** [comment]
Yup same here.  Would love to get this on PyPI as soon as possible

**Comment by elsigh** [comment]
I don't know if anyone is super actively deploying to pypi these days for the repo. If so, my bad, but if not.. I've seen a few issues around python distribution over the last two months and would love for someone to step up and own that.

**Comment by kr41** [comment]
@elsigh could you open tickets for the issues you've seen? I'll try to solve them and send pull requests.

**Comment by dsimandl** [comment]
If sdist is working then setup,py upload to PyPI should just work yes?  (Sorry I don't a lot of experience uploading projects to PyPI)

**Comment by mattrobenolt** [comment]
@elsigh I wouldn't mind helping out here a bit. Let me know.

**Comment by nass600** [comment]
Any news?

**Comment by bevedoni** [comment]
any news guys?

**Comment by elsigh** [comment]
I think the issue is that I don't know how to push to pypi and I'm not using uap-python in production, so I have no interest in doing so - and there's not really anyone who's on it who wants to actively do so for the project.

**Comment by mattrobenolt** [comment]
@elsigh I've volunteered. :)

**Comment by elsigh** [comment]
Ok! I'll add you as a committer and thank you!!!

**Comment by mattrobenolt** [comment]
@elsigh Could you add me to pypi as well plz? :)

I can get this sorted out this week.

**Comment by elsigh** [comment]
@mattrobenolt I have no idea how to do that, can you tell me? I don't have a pypi account or "own" our pypi build or anything (at least I don't believe I do!)

**Comment by mattrobenolt** [comment]
It appears that @selwin is the package owner on pypi.

**Comment by nass600** [comment]
Any update on this guys?

**Comment by mattrobenolt** [comment]
I still don't have access to upload a new version. :sob: 

/cc @selwin

**Comment by selwin** [comment]
Sorry for the late reply. Version 0.5.1 is now up on PyPI. Also submitted a PR to bump up the version number to 0.5.1 here: https://github.com/ua-parser/uap-python/pull/36
