### ISSUE TITLE
IndexError: no such group for Mozilla/5.0 (Linux; U; Android 4.1.1; en-us; Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30

### ISSUE THREAD

**Issue by rickjury** [ua-parser/uap-python#47]
this user agent string fails to parse:
user_agent_parser.Parse('Mozilla/5.0 (Linux; U; Android 4.1.1; en-us; Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30')
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\ua_parser-0.4.0-py2.7.egg\ua_parser\user_agent_parser.py", line 212, in Parse
    'device': ParseDevice(user_agent_string, **jsParseBits),
  File "C:\Python27\lib\site-packages\ua_parser-0.4.0-py2.7.egg\ua_parser\user_agent_parser.py", line 291, in ParseDevice
    device, brand, model = deviceParser.Parse(user_agent_string)
  File "C:\Python27\lib\site-packages\ua_parser-0.4.0-py2.7.egg\ua_parser\user_agent_parser.py", line 187, in Parse
    device = match.group(1)
IndexError: no such group

**Comment by mattrobenolt** [comment]
I'm unable to reproduce this on the latest version 0.7.2. The version you have here (0.4.0) is pretty old. You should update.
